# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# Site settings
url: 'https://financie.ga'
baseurl: ''
title: 'Webové stránka o peniazoch'
description: 'Webové stránka o peniazoch a iné veci'
permalink: pretty

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  Blog: /blog/

# Footer nav
navigation_footer:

# Collections
collections:
  posts:
    title: Clánky
    output: true
    feature_text: |
      Vítajte
    feature_image: "https://picsum.photos/2560/600?image=866"
